### ISSUE TITLE
Support log appender/handler configuration

### ISSUE THREAD

**Issue by codeboten** [MrAlias/otel-schema#22]
Follow up from #20, users must have a way to specify hooking up log appenders/handlers to the logging provider.

The wiring up of appenders to the SDK seems more like an instrumentation concern than an SDK concern. I suggest we include that under the `instrumentation` section. I.e. something like:
```
sdk:
  ...
instrumentation:
  log_appenders:
    - name: log4j
    - name: logback
```

_Originally posted by @jack-berg in https://github.com/MrAlias/otel-schema/pull/20#discussion_r1040101928_

**Comment by codeboten** [comment]
We may want to add this under a language-specific section:

```
sdk:
  ...
instrumentation:
  ...
java:
  log_appenders:
    - name: log4j
    - name: logback
python:
  log_handlers:
    - name: logging
```
