### ISSUE TITLE
Should config validation ensure configured components are available?

### ISSUE THREAD

**Issue by codeboten** [MrAlias/otel-schema#29]
One question that came to mind as I was reviewing #26 is whether configuration validation should be responsible for validating that configured components are available. For example if I configure the xray propagator but the propagator is not available in my system, will configuration validation tell me this or will it load the config (assuming its configured properly) and let the SDK fail?

**Comment by svrnm** [comment]
what if there is a default (print a warning but just continue starting the app) but it can be overwriten with an additional property?

```yaml
  propagators:
    - name: tracecontext
    - name: baggage
      failIfNotPresent: true
```
